# Generated by Django 5.2.1 on 2025-05-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
